name: TourGuide CI/CD

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test
        run: mvn clean install

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: tourguide-app
          path: target/*.jar